name: Build and Test Firmware

on:
  push:
    branches:
      - dev
      - 'feature/**'
    paths:
      - 'firmware/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'firmware/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make

      - name: Build Firmware
        run: |
          cd firmware
          make all

      - name: Run Unit Tests
        run: |
          cd firmware/tests
          make test
